### ISSUE TITLE
Freezing on MacOS

### ISSUE THREAD

**Issue by jaroet** [planetsizecpu/forms#1]
Tried running latest on MacOS Got a frozen GUI (it did start). Only seeing the beachball shaped mouse cursor. I am able to move the windows around but everything else is not responding.

**Comment by planetsizecpu** [comment]
ah thx for the input, I'm unable to test on MacOS, just testing in w7 and w10. There are some issues to be corrected, as for example the one related to run button, after it run on 'do' interpreter all widgets would belong to another window, I have to deep inspect and gave it solution, but I'm on a lack of time now.

**Comment by planetsizecpu** [comment]
I have made some updates in screen arrangement, so you may test again.
